/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import model.Conta;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.text.ParseException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Collections;
import java.util.EnumSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFormattedTextField;
import javax.swing.text.MaskFormatter;
import model.*;
import static model.TipoReceita.Decimo_Terceiro;
import static model.TipoReceita.Ferias;
import static model.TipoReceita.Outras_Receitas;
import static model.TipoReceita.Salario;

/**
 * JFrame principal da aplicação para registro de transações financeiras.
 * Esta classe controla a interface gráfica e a lógica por trás das operações
 * de adição e listagem de transações.
 * 
 * Esta classe representa a interface gráfica e manipula as transações de receitas e despesas.
 * 
 * @author cdran
 * 
 * @see Transacao
 * @see Conta
 * @see ExportadorArquivo
 * @see ImportadorArquivo
 * @see TipoTransacao
 * @see TipoDespesa
 * @see TipoReceita
 * @see OrdenacaoPorDataDecrescente
 */
public class App extends javax.swing.JFrame{

    Conta conta = new Conta();
    Transacao transacao = new Transacao();
    ExportadorArquivo exportador = new ExportadorArquivo();
    ArrayList<Transacao> lista = new ArrayList<>();
    File arquivo;
    String path;

    /**
     * Construtor padrão da classe App.
     * Inicializa os componentes da interface gráfica e define os listeners
     * para os eventos dos radio buttons de receita e despesa.
     */
    public App() {
        initComponents();

        rbDespesa.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                updateComboBox(TipoTransacao.Despesa);
            }
        });

        rbReceita.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                updateComboBox(TipoTransacao.Receita);
            }
        });

    }
    /**
     * Método privado para atualizar as opções do combo box de acordo com o tipo
     * de transação selecionada (receita ou despesa).
     *
     * @param tipoTransacao Tipo de transação selecionada (Receita ou Despesa)
     */
    private void updateComboBox(TipoTransacao tipoTransacao) {
        cbTipo.removeAllItems();

        EnumSet<?> enumSet;
        if (tipoTransacao == TipoTransacao.Despesa) {
            enumSet = EnumSet.allOf(TipoDespesa.class);
        } else {
            enumSet = EnumSet.allOf(TipoReceita.class);
        }

        for (Object enumValue : enumSet) {
            cbTipo.addItem(enumValue.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
   /**
     * Este método é chamado de dentro do construtor para inicializar o formulário.
     * AVISO: Não modifique este código. O conteúdo deste método é sempre
     * regenerado pelo Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgTransacoes = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        rbReceita = new javax.swing.JRadioButton();
        rbDespesa = new javax.swing.JRadioButton();
        cbTipo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfData = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        tfValor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btListar = new javax.swing.JButton();
        btAdicionar = new javax.swing.JButton();
        jlAdd = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Controlador de Transações");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Titular"));

        jLabel1.setText("Nome do Titular:");

        tfNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Transação"));

        jLabel2.setText("Tipo de Transação:");

        bgTransacoes.add(rbReceita);
        rbReceita.setText("Receita");
        rbReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbReceitaActionPerformed(evt);
            }
        });

        bgTransacoes.add(rbDespesa);
        rbDespesa.setText("Despesa");
        rbDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDespesaActionPerformed(evt);
            }
        });

        cbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoActionPerformed(evt);
            }
        });

        jLabel3.setText("Tipo Receita/Despesa:");

        jLabel4.setText("Data da Transação:");

        tfData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDataActionPerformed(evt);
            }
        });

        jLabel5.setText("Valor da Transação:");

        tfValor.setToolTipText("");
        tfValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfValorActionPerformed(evt);
            }
        });

        jLabel6.setText("R$");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rbReceita)
                        .addGap(50, 50, 50)
                        .addComponent(rbDespesa))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addGap(7, 7, 7)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tfData)
                                .addComponent(tfValor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(rbReceita)
                    .addComponent(rbDespesa))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        cbTipo.getAccessibleContext().setAccessibleName("teste");

        btListar.setText("Listar");
        btListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btListarActionPerformed(evt);
            }
        });

        btAdicionar.setText("Adicionar");
        btAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarActionPerformed(evt);
            }
        });

        jlAdd.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btListar)
                        .addGap(18, 18, 18)
                        .addComponent(btAdicionar)
                        .addGap(18, 18, 18)
                        .addComponent(jlAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btListar)
                    .addComponent(btAdicionar)
                    .addComponent(jlAdd))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomeActionPerformed

    private void rbReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbReceitaActionPerformed
        // TODO add your handling code here:   
    }//GEN-LAST:event_rbReceitaActionPerformed

    private void cbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoActionPerformed
        // TODO add your handling code here: 
    }//GEN-LAST:event_cbTipoActionPerformed

    private void rbDespesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDespesaActionPerformed
        // TODO add your handling code here: 
    }//GEN-LAST:event_rbDespesaActionPerformed

    private void tfDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDataActionPerformed
    /**
     * Listener para o evento de adição de transação.
     * Este método é chamado quando o botão "Adicionar Transação" é clicado.
     * Ele realiza a validação dos campos, cria uma nova transação com os
     * valores fornecidos e a adiciona à lista de transações da conta.
     *
     * @param evt O evento de clique do botão
     */
    private void btAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionarActionPerformed

        ImportadorArquivo ia = new ImportadorArquivo();
        ExportadorArquivo ea = new ExportadorArquivo();

        // Defina o caminho do arquivo
        path = ("bin\\bin.csv");  
        arquivo = new File(path);
        // Verifique se o arquivo existe

        ia.setArquivo(arquivo);
        ea.setFile(arquivo);
        ia.processarArquivo();

        ArrayList<Transacao> lista = ia.getTransacoes();
        String nome = tfNome.getText();
        
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        LocalDate data = LocalDate.parse(tfData.getText(), formatter);
        
        double valor = Double.parseDouble(tfValor.getText());

        transacao.setDate(data);
        transacao.setValor(valor);
        
        Conta conta1 = new Conta();
        // Defina o tipo de transação
        if (rbReceita.isSelected()) {
            Receitas receita = new Receitas();
            receita.setTipoTransacao(TipoTransacao.Receita);
            receita.setTipoReceita(TipoReceita.valueOf(cbTipo.getSelectedItem().toString()));
            receita.setDescricao(nome);
            receita.setDate(data);
            receita.setValor(valor);
            
            ea.gravarArquivo(lista);
            
            conta1.setNomeTitular(nome);
            conta1.setTransacoes(lista);
            conta1.saldoAteDataAtual();
            conta1.saldoTotal();
            
            lista.add(receita);


        } else if (rbDespesa.isSelected()) {
            Despesas despesa = new Despesas();
            despesa.setTipoTransacao(TipoTransacao.Despesa);
            despesa.setTipoDespesa(TipoDespesa.valueOf(cbTipo.getSelectedItem().toString()));
            despesa.setDescricao(nome);
            despesa.setDate(data);
            despesa.setValor(valor);

            conta1.setNomeTitular(nome);
            conta1.setTransacoes(lista);
            conta1.saldoAteDataAtual();
            conta1.saldoTotal();
            
            lista.add(despesa);
            ea.gravarArquivo(lista);
        }

        // Ordene a lista de transações
        Collections.sort(lista, new OrdenacaoPorDataDecrescente());

        // Grave a lista atualizada de transações no arquivo
        ea.gravarArquivo(lista);
        
        if (arquivo.exists()) {
            System.out.println("Arquivo encontrado: " + arquivo.getAbsolutePath());
        } else {
            System.out.println("Arquivo não encontrado.");
        }
        // Atualize a mensagem de transação registrada e repinte o label
        jlAdd.setText("Transação Registrada");
        jlAdd.repaint();
    }//GEN-LAST:event_btAdicionarActionPerformed

    private void tfValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfValorActionPerformed
    /**
     * Listener para o evento de listagem de transações.
     * Este método é chamado quando o botão "Listar Transações" é clicado.
     * Ele mostra todas as transações registradas na conta até o momento.
     *
     * @param evt O evento de clique do botão
     */
    private void btListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btListarActionPerformed
        ListaTransacoes lista2 = new ListaTransacoes(this, true);

        lista2.setVisible(true);

    }//GEN-LAST:event_btListarActionPerformed

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }

     /**
     * Método principal que inicia a aplicação.
     * Cria uma instância da classe App (JFrame) e a torna visível.
     *
     * @param args Os argumentos de linha de comando (não utilizados neste caso)
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgTransacoes;
    private javax.swing.JButton btAdicionar;
    private javax.swing.JButton btListar;
    private javax.swing.JComboBox<String> cbTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jlAdd;
    private javax.swing.JRadioButton rbDespesa;
    private javax.swing.JRadioButton rbReceita;
    private javax.swing.JFormattedTextField tfData;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfValor;
    // End of variables declaration//GEN-END:variables

}
