/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Categorias;
import static model.Categorias.*;
import model.Prioridades;
import static model.Prioridades.*;
import model.Utilitario;

/**
 *
 * @author user
 */
public class App_InserirLinha extends javax.swing.JFrame {

    private App app;

    /**
     * Creates new form App_InserirLinha
     */
    public App_InserirLinha(App app) {
        this.app = app;
        initComponents();

        Utilitario u = new Utilitario();
        u.InserirIcone(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jText_tarefaIncluir = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jCombo_prioridadeIncluir = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jCombo_categoriaIncluir = new javax.swing.JComboBox<>();
        jb_IncluirLinha = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Incluir Linha");

        jLabel1.setText("Tarefa:");

        jLabel2.setText("Prioridade:");

        jCombo_prioridadeIncluir.setModel(
                new javax.swing.DefaultComboBoxModel<>(new String[] { "Urgente", "Alta", "Média", "Baixa", "Miníma" }));
        jCombo_prioridadeIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCombo_prioridadeIncluirActionPerformed(evt);
            }
        });

        jLabel3.setText("Categoria:");

        jCombo_categoriaIncluir.setModel(new javax.swing.DefaultComboBoxModel<>(
                new String[] { "Alimentação", "Profissional", "Estudo", "Lazer", "Saúde", "Educação", "Outros" }));

        jb_IncluirLinha.setText("Incluir");
        jb_IncluirLinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_IncluirLinhaActionPerformed(evt);
            }
        });

        // Adicionando o KeyListener para o campo de texto da tarefa
        jText_tarefaIncluir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                    jb_IncluirLinha.doClick(); // Simula o clique no botão
                }
            }
        });

        // Adicionando o KeyListener para o combo de prioridade
        jCombo_prioridadeIncluir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                    jb_IncluirLinha.doClick(); // Simula o clique no botão
                }
            }
        });

        // Adicionando o KeyListener para o combo de categoria
        jCombo_categoriaIncluir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                    jb_IncluirLinha.doClick(); // Simula o clique no botão
                }
            }
        });
        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(20, 20, 20)
                                                .addComponent(jText_tarefaIncluir,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 296,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jLabel3)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jCombo_categoriaIncluir,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 157,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jLabel2)
                                                                .addGap(14, 14, 14)
                                                                .addComponent(jCombo_prioridadeIncluir,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 158,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jb_IncluirLinha)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(jText_tarefaIncluir, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(jCombo_prioridadeIncluir, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(jCombo_categoriaIncluir, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jb_IncluirLinha))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_IncluirLinhaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jb_IncluirLinhaActionPerformed
        // TODO add your handling code here:

        String tarefaIncluir = jText_tarefaIncluir.getText();
        String prioridadeIncluir = (String) jCombo_prioridadeIncluir.getSelectedItem();
        String categoriaIncluir = (String) jCombo_categoriaIncluir.getSelectedItem();
        boolean concluidoIncluir = false; // inicialmente, a tarefa não está concluida

        Prioridades prioridade = null;
        Categorias categoria = null;

        switch (prioridadeIncluir) {
            case "Urgente" ->
                prioridade = URGENTE;
            case "Alta" ->
                prioridade = ALTA;
            case "Média" ->
                prioridade = MEDIA;
            case "Baixa" ->
                prioridade = BAIXA;
            case "Miníma" ->
                prioridade = MINIMA;
        }

        switch (categoriaIncluir) {
            case "Alimentação" ->
                categoria = ALIMENTACAO;
            case "Profissional" ->
                categoria = PROFISSIONAL;
            case "Transporte" ->
                categoria = TRANSPORTE;
            case "Estudo" ->
                categoria = ESTUDO;
            case "lazer" ->
                categoria = LAZER;
            case "Saúde" ->
                categoria = SAUDE;
            case "Educação" ->
                categoria = EDUCACAO;
            case "Outros" ->
                categoria = OUTROS;
        }
        // Verifica se os campos obrigatórios estão preenchidos
        if (tarefaIncluir.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Os campos devem ser preenchidos corretamente!", "Erro",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        app.adicionarLinhaTabela(tarefaIncluir, prioridade, categoria, concluidoIncluir);
        app.adicionarTarefa(tarefaIncluir, prioridade, categoria, concluidoIncluir);
        app.recalcular();
        this.dispose();// fecha a tela
    }// GEN-LAST:event_jb_IncluirLinhaActionPerformed

    private void jCombo_prioridadeIncluirActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jCombo_prioridadeIncluirActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jCombo_prioridadeIncluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App_InserirLinha.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App_InserirLinha.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App_InserirLinha.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App_InserirLinha.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                App app;
                try {
                    app = new App();
                } catch (IOException ex) {
                    Logger.getLogger(App_InserirLinha.class.getName()).log(Level.SEVERE, null, ex);
                }
                // new App_InserirLinha(app).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jCombo_categoriaIncluir;
    private javax.swing.JComboBox<String> jCombo_prioridadeIncluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jText_tarefaIncluir;
    private javax.swing.JButton jb_IncluirLinha;
    // End of variables declaration//GEN-END:variables
}
